Fix/get top fashion cities names
red-velvet-cake-organization/cost-of-living pull request #46
Opened 2023-02-18 16:28 UTC by devsadeq

2023-02-18 16:56 UTC, flutterdevtaha approved these changes
well done 🥰

2023-02-18 19:44 UTC, MahmoudAkramAlMallahi approved these changes

2023-02-18 21:13 UTC, ma28alhams requested changes
- Add a test case to check if all the data has been filtered, then should return an empty list.

2023-02-18 21:13 UTC, ma28alhams commented on src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
>      fun `should return only the required number of results`() {
```suggestion
    fun `should return only the required number of cities`() {
```

2023-02-18 21:13 UTC, ma28alhams commented on src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
> +        val actual = interactor.execute(limit).size
Are you sure about this test case?
Is it make sense?

2023-02-18 21:13 UTC, ma28alhams commented on src/main/kotlin/utils/Constants.kt
>  object Constants {
use **companion object** instead of object

2023-02-19 00:34 UTC, devsadeq commented on src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
> +            .ifEmpty { throw NoReturnedDataException(EMPTY_DATA_SOURCE_EXCEPTION_MSG) }
Already done

2023-02-19 00:35 UTC, devsadeq commented on src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
> +            .distinctBy { it.cityName to it.country }
To get a unique cities, no duplications

2023-02-19 00:36 UTC, devsadeq commented on src/main/kotlin/interactor/GetCityMatchManagerExpectationsInteractor.kt
>              .minByOrNull(::getMidRangePrices)
This code is not mine. I just resolve a conflict here. It's belong to Taha.

2023-02-19 00:38 UTC, devsadeq commented on src/main/kotlin/interactor/GetCityMatchManagerExpectationsInteractor.kt
>              .minByOrNull(::getMidRangePrices)
This also belong to @flutterdevtaha 😅

2023-02-19 00:40 UTC, devsadeq commented on src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
> +        val actual = interactor.execute(limit).size
Actually, this text case save me several times so I think I need it.

2023-02-19 00:52 UTC, devsadeq commented on src/main/kotlin/utils/Constants.kt
>  object Constants {
How to do that exactly?

https://github.com/Salmon-family/Clubs/blob/master/core/ui/src/main/java/com/devfalah/ui/util/Constants.kt

2023-02-19 01:00 UTC, devsadeq commented
I'm not get it 👀 @ma28alhams

2023-02-19 03:30 UTC, ma28alhams commented on src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
> +            .distinctBy { it.cityName to it.country }
Why distincting by **Pair** ?

2023-02-19 03:35 UTC, ma28alhams commented on src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
> +        val actual = interactor.execute(limit).size
I think Bariq said that we should not compare the size of the arrays to each other, but rather compare the two arrays.

2023-02-19 03:42 UTC, ma28alhams commented on src/main/kotlin/utils/Constants.kt
>  object Constants {
Object used as Singelton pattern,
But companion object used to declare members as static members.

https://medium.com/mindorks/kotlin-object-vs-companion-object-a1907c76a2af

2023-02-19 07:33 UTC, flutterdevtaha commented on src/main/kotlin/interactor/GetCityMatchManagerExpectationsInteractor.kt
>              .minByOrNull(::getMidRangePrices)
I will edit on @ma28alhams

2023-02-19 07:35 UTC, flutterdevtaha commented on src/main/kotlin/utils/Constants.kt
>  object Constants {
@ma28alhams that is more correct becuase it is shared across the app

2023-02-19 07:36 UTC, merged

2023-02-19 12:33 UTC, devsadeq commented on src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
> +            .distinctBy { it.cityName to it.country }
Cause there are many counties that have same name of cities.