fix / get city that has lowest cost of food
red-velvet-cake-organization/cost-of-living pull request #50
Opened 2023-02-18 19:23 UTC by NabaaArt

2023-02-18 22:35 UTC, ma28alhams requested changes
Please then change the test cases for that task depend on the changes in the logic

2023-02-18 22:35 UTC, ma28alhams commented on src/main/kotlin/interactor/GetCityThatHasLowestCostOfFoodInteractor.kt
> +    fun execute(): List<Pair<String, Float>> {
Change the return type to CityEntity,
Because it just returns the **ONE** lowest city
```suggestion
    fun execute(): CityEntity {
```

2023-02-18 22:35 UTC, ma28alhams commented on src/main/kotlin/interactor/GetCityThatHasLowestCostOfFoodInteractor.kt
> +) : CostOfLivingDataSource {
Remove the implementation of the CostOfLivingDataSource interface
```suggestion
)  {
```

2023-02-18 22:35 UTC, ma28alhams commented on src/main/kotlin/interactor/GetCityThatHasLowestCostOfFoodInteractor.kt
> +            }
```suggestion
            .getAllCitiesData()
            .ifEmpty{ throw IllegalStateException() }
            .filter(::excludeNullFoodPricesAndLowQualityData)
            .minByOrNull{ it.getCostOfFood() } 
            ?: throw NoSuchElementException("No any city matching the given condition")
```

2023-02-18 22:35 UTC, ma28alhams commented on src/main/kotlin/interactor/GetCityThatHasLowestCostOfFoodInteractor.kt
> +        TODO("Not yet implemented")
Delete this overridden method

2023-02-18 22:35 UTC, ma28alhams commented on src/main/kotlin/interactor/GetCityThatHasLowestCostOfFoodInteractor.kt
> +            && city.dataQuality
```suggestion
    return city.foodPrices.loafOfFreshWhiteBread500g.isNotNull()
            city.foodPrices.chickenFillets1kg.isNotNull()
            city.foodPrices.eggsRegular12.isNotNull()
            city.foodPrices.riceWhite1kg.isNotNull()
            city.foodPrices.localCheese1kg.isNotNull()
            city.foodPrices.beefRound1kgOrEquivalentBackLegRedMeat.isNotNull()
            && city.dataQuality
```

2023-02-18 22:35 UTC, ma28alhams commented on src/main/kotlin/interactor/GetCityThatHasLowestCostOfFoodInteractor.kt
> +    Exception (message)
Delete this exception

2023-02-19 07:24 UTC, flutterdevtaha requested changes

2023-02-19 07:24 UTC, flutterdevtaha commented on src/main/kotlin/interactor/GetCityThatHasLowestCostOfFoodInteractor.kt
> +    fun execute(): List<Pair<String, Float>> {
@NabaaArt please do what @ma28alhams asks for changes

2023-02-19 14:37 UTC, NabaaArt commented
@ma28alhams @flutterdevtaha 
thanks

2023-02-19 15:32 UTC, ma28alhams approved these changes

2023-02-19 16:01 UTC, merged